### ISSUE TITLE
TypeError: chas type int32 that does not match expected type of float32.

### ISSUE THREAD

**Issue by jz1998** [waitingfordark/four_flower#18]
TypeError: Input 'predictions' of 'InTopKV2' Op has type int32 that does not match expected type of float32.

这个怎么解决啊，在GitHub上看到有人提问过，说加上
`logits = tf.cast(logits, "float32")
    labels = tf.cast(labels, "int32")`
不过还是报错了

**Comment by jz1998** [comment]
这些问题都是因为TensorFlow的版本，重新在anaconda里面新建一个环境然后安装新的TensorFlow1.X的版本就可以！

**Comment by waitingfordark** [comment]
使用Tensorflow-v2可以加上`tensorflow.compat.v1.disable_eager_execution()`，但是最好改为tf.data。
