### ISSUE TITLE
测试数据集

### ISSUE THREAD

**Issue by Snaill123** [waitingfordark/four_flower#3]
您好，test.py的main函数中用到的flower_photos数据集好像没在github上

**Comment by bighansome** [comment]
test你应该使用自己的图片，搜索引擎找这几种花的图片来测试

**Comment by Snaill123** [comment]
好的，谢谢

**Comment by CatbossMr** [comment]
您好，我用的是vs2017，训练过程没问题，请问一下我在测试过程中一直报错Attempting to use uninitialized value local4/weights，或者ckpt一直为空，无法导入怎么办呢？

**Comment by kaiupup** [comment]
大佬，一张图里的向日葵多了就会识别出郁金香，我想问问至少要多少张图片才可以让识别效果才能比较准确，求回复
